// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wbraqbcixhfnrejitusf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndicmFxYmNpeGhmbnJlaml0dXNmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3NTA1NTgsImV4cCI6MjA2NjMyNjU1OH0.vbA1_qlAgOp1mLOH97cORnGI32pcN9ORA1hs56OOe3I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);